require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PageTextsController do

  def mock_page_text(stubs={})
    @mock_page_text ||= mock_model(PageText, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all page_texts as @page_texts" do
      PageText.stub(:all) { [mock_page_text] }
      get :index
      assigns(:page_texts).should eq([mock_page_text])
    end
  end

  describe "GET show" do
    it "assigns the requested page_text as @page_text" do
      PageText.stub(:find).with("37") { mock_page_text }
      get :show, :id => "37"
      assigns(:page_text).should be(mock_page_text)
    end
  end

  describe "GET new" do
    it "assigns a new page_text as @page_text" do
      PageText.stub(:new) { mock_page_text }
      get :new
      assigns(:page_text).should be(mock_page_text)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_text as @page_text" do
      PageText.stub(:find).with("37") { mock_page_text }
      get :edit, :id => "37"
      assigns(:page_text).should be(mock_page_text)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created page_text as @page_text" do
        PageText.stub(:new).with({'these' => 'params'}) { mock_page_text(:save => true) }
        post :create, :page_text => {'these' => 'params'}
        assigns(:page_text).should be(mock_page_text)
      end

      it "redirects to the created page_text" do
        PageText.stub(:new) { mock_page_text(:save => true) }
        post :create, :page_text => {}
        response.should redirect_to(page_text_url(mock_page_text))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_text as @page_text" do
        PageText.stub(:new).with({'these' => 'params'}) { mock_page_text(:save => false) }
        post :create, :page_text => {'these' => 'params'}
        assigns(:page_text).should be(mock_page_text)
      end

      it "re-renders the 'new' template" do
        PageText.stub(:new) { mock_page_text(:save => false) }
        post :create, :page_text => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_text" do
        PageText.stub(:find).with("37") { mock_page_text }
        mock_page_text.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :page_text => {'these' => 'params'}
      end

      it "assigns the requested page_text as @page_text" do
        PageText.stub(:find) { mock_page_text(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:page_text).should be(mock_page_text)
      end

      it "redirects to the page_text" do
        PageText.stub(:find) { mock_page_text(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(page_text_url(mock_page_text))
      end
    end

    describe "with invalid params" do
      it "assigns the page_text as @page_text" do
        PageText.stub(:find) { mock_page_text(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:page_text).should be(mock_page_text)
      end

      it "re-renders the 'edit' template" do
        PageText.stub(:find) { mock_page_text(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_text" do
      PageText.stub(:find).with("37") { mock_page_text }
      mock_page_text.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the page_texts list" do
      PageText.stub(:find) { mock_page_text }
      delete :destroy, :id => "1"
      response.should redirect_to(page_texts_url)
    end
  end

end
